### ISSUE TITLE
Regexp injection

### ISSUE THREAD

**Issue by mmzoo** [gchan/password_blacklist#1]
This:

```ruby
PasswordBlacklist::Checker.new.blacklisted? ')'
```

will cause a

```
RegexpError: unmatched close parenthesis: /)/
```

Similarly

```ruby
PasswordBlacklist::Checker.new.blacklisted? '.*'
```

Always returns `true` because of it is not interpreted as a verbatim string.

Could you please use

```ruby
/#{Regexp.quote(password.to_s)}/
```

In your [check](https://github.com/gchan/password_blacklist/blob/master/lib/password_blacklist/checker.rb#L10)?

Thank you!

**Comment by gchan** [comment]
This has been fixed! Thanks for reporting the issue!

**Comment by mmzoo** [comment]
That was quick :) Thank **you**!
